"""Added primary key constraint to inventory_issue_types

Revision ID: a614242431a3
Revises: dfedbabbe28b
Create Date: 2026-05-17 21:13:18.872858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a614242431a3'
down_revision: Union[str, None] = 'dfedbabbe28b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
