"""Added fields to ticket model

Revision ID: d6d84e97ebae
Revises: efad473433b5
Create Date: 2026-05-19 18:52:40.572298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d84e97ebae'
down_revision: Union[str, None] = 'efad473433b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('is_urgent', sa.Boolean(), nullable=False))
    op.add_column('tickets', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tickets', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'completed_at')
    op.drop_column('tickets', 'started_at')
    op.drop_column('tickets', 'is_urgent')
    # ### end Alembic commands ###
