"""some fixes

Revision ID: d99c58e7a557
Revises: 0ce7d0251bd4
Create Date: 2026-05-18 17:43:19.078549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99c58e7a557'
down_revision: Union[str, None] = '0ce7d0251bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_inventory_issue_types_inventory_type_id'), 'inventory_issue_types', ['inventory_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_issue_types_inventory_type_id'), table_name='inventory_issue_types')
    # ### end Alembic commands ###
